innosat-mats/MATS-L1-processing

non-linearity/non_linearity_simulation.py, non-linearity/non_linerity_simulation.ipynb, non-linearity/run_non_linearity.py, src/database_generation/binning_functions.py, src/database_generation/linearity.py, src/database_generation/read_in_imgview_functions.py, src/mats_l1_processing/L1_calibration_functions.py
=> Non linearity

src/mats_l1_processing/L1b_calibration_functions.py
I am ready to merge the UV1 alignment.
=> Issue 58: Updated UV1 alignment shift position

src/mats_l1_processing/read_in_functions.py
Abstracted out reading of metadata to easier sort the data
=> Added possibility to read .csv file seperatelly

.github/workflows/cd.yml
Was running `cdk deploy` from wrong working directory.
=> Run CDK from correct directory

.github/workflows/cd.yml, .gitignore, l1b_lambda/Dockerfile, l1b_lambda/app.py, l1b_lambda/level1b/handlers/level1b.py, l1b_lambda/stacks/level1b_stack.py, l1b_lambda/tests/level1b/handlers/test_level1b.py, l1b_lambda/tox.ini
Update to using a Docker based lambda. Instrument files are downloaded to the build service from the S3 bucket using aws cli.
=> Use docker lambda

l1b_lambda/app.py
Part of https://github.com/innosat-mats/level1a-platform/issues/10
=> Update new bucket versions

src/mats_l1_processing/L1_calibrate.py, src/mats_l1_processing/instrument.py, src/mats_l1_processing/pointing.py, tests/calibration_data_test.toml, tests/test_calibration.py
=> Adding qprime quaternion that maps from channel to OHB body frame #

.github/workflows/cd.yml
=> Lock deploy to use deploy branch

src/mats_l1_processing/L1_calibrate.py, src/mats_l1_processing/L1_calibration_functions.py, src/mats_l1_processing/instrument.py, tests/calibration_data_test.toml, tests/test_calibration.py
Added default temperature where temperature data is missing. Note that calibration.toml file needs to be updated
=> Fixed issue #102 

src/mats_l1_processing/pointing.py
=> fixed a keys space problem in pointing

src/mats_l1_processing/L1_calibration_functions.py
This is a fix for the NRSKIP + nrow*nrbin  >511  which should have caused a different error that it did
aa=np.arange(10)
print(aa[2:2+3] ,aa[2:2+13] )
dum python
And a repeated NCSKIP instead of and NRSKIP NCSKIP in the test at line 546
=> fixed binning to cope nrskip too big + bug in 546

l1b_lambda/app.py, l1b_lambda/level1b/handlers/level1b.py
This adds the following items from `CCDItem` to the L1B parquet files:
- `channel`
- `flipped`
- `temperature`
- `temperature_HTR`
- `temperature_ADC`
Resolves #110
=> Add missing attributes

.github/workflows/cd.yml
=> Add token to CD workflow

src/mats_l1_processing/read_parquet_functions.py
=> Fix missing import

.github/workflows/cd-dev.yml, l1b_lambda/app.py, l1b_lambda/stacks/level1b_stack.py
New continuous deployment workflow for development.
The intent is that this should be deployed from the `development` branch, but it has been set up so that it _can_ be deployed from other branches as well. This should be safe to merge into the `deployment` branch, since that uses a different workflow, which does not set the required environment variable.
Resolves #131
=> New CD workflow for development

src/mats_l1_processing/read_parquet_functions.py
Improves performance for slow internet connections. See issue #138
=> read_ccd_data_in_interval now uses partitioning for faster accessing

src/mats_l1_processing/read_parquet_functions.py
it is similar to read_ccd_data_in_interval but is adapted to the partitioning of level 0 data other than CCD
=> adding read_intsrument_data_in_interval function

src/mats_l1_processing/L1_calibrate.py
the L1_calibrate outputs are changed : image_lsb_no_art (after artifact correction) is added and image_calib_no_art is removed the order of the errorflags are not changed
=> moving artifact_correction function to be the first correction applied

src/mats_l1_processing/L1_calibrate.py, tests/test_calibration.py
Moving the artifact correction step as the last correction to be applied.
=> Artifact correction last step

src/mats_l1_processing/L1_calibration_functions.py
flipping nadir channel left to right, solving issue 129
resolves #129
=> Flipping NADIR channel left ringt.

src/mats_l1_processing/L1_calibrate.py, src/mats_l1_processing/L1_calibration_functions.py, tests/test_calibration.py
added meadian filter option to desmear
renamed partial calibrated images
removed artifact correction
added calibration image plots for test_calibration
=> added optionallty to images returned from calibration function

src/mats_l1_processing/L1_calibrate.py, src/mats_l1_processing/L1_calibration_functions.py
Added error flag for when flatfield correction is larger than 5%
=> Added error flag for when flatfield correction is larger than 5%

src/mats_l1_processing/read_parquet_functions.py
that is reverses the functions that go from ccditems to df.
=> Added two functions to go from df to ccditems ,

l1b_lambda/app.py, l1b_lambda/level1b/handlers/level1b.py
Adjust memory and storage to accommodate the larger HP/SE database.
Also paperclipped handling of the fact that Image can apparently be `None` now...
=> Adjust memorny and storage

.gitignore, src/database_generation/experimental_utils.py, src/mats_l1_processing/L1_calibration_functions.py
-fixed single event bug.
- added some functionality to plotting script plot_CCDimage
This fixes issue #233
=> fixed single event bug issue 233
