innosat-mats/MATS-L1-processing

l1b_lambda/Dockerfile
Command in lambda docker was pointing to a non-existent method. I have manually verified that this version can deploy and run.
=> Fix cmd in Dockerfile

l1b_lambda/level1b/handlers/level1b.py
This adds explicit printout of errors in lambda, so that we can (hopefully) follow what's going on in cloudwatch.
Relates to #85
=> Better error reporting in lambda

l1b_lambda/.dockerignore, l1b_lambda/Dockerfile, l1b_lambda/level1b/handlers/level1b.py, l1b_lambda/stacks/level1b_stack.py
This fixes the docker-build, as well as most other small issues. After this, processing works, provided the number of images per batch are few enough.
Resolves #85
=> Fix docker build

l1b_lambda/app.py
Bumps versions in anticipation of new partitioning. Note that buckets will need to be created.
We should also empty the DLQ.
=> Bump in- and output versions

l1b_lambda/level1b/handlers/level1b.py
This converts the calibrated image to a nested list before storing it. For some reason 2d-arrays don't work out of the box, but this seems to do...
Calibration Errors need the same treatment, apparently.
Resolves #100
=> Convert calibrated image to list before storing

l1b_lambda/level1b/handlers/level1b.py
This propagates `qprime` to the L1B record. This fixes the code part of #106, but the data will need to be re-run. That should probably wait until after #101 and #107 have been merged as well, though.
=> Propagate qprime

l1b_lambda/level1b/handlers/level1b.py, src/mats_l1_processing/L1_calibrate.py, src/mats_l1_processing/L1_calibration_functions.py
This propagates the `force_table` argument from `get_linearized_image` to `L1_calibrate` and sets it to `False` for Lambda batch-processing, where the file system is read only.
I'm not sure if this will ruin something else in your workflows, @innosat-mats/scientific . I don't think so, but please review carefully!
Resolves #103
=> Set force_table=False in Lambda processing

l1b_lambda/level1b/handlers/level1b.py
Replacing metadata was not done in place. This corrects the updating, as well as adds a few attributes to more easily identify contents and origins of the file.
=> Actually save metadata

src/mats_l1_processing/L1_calibration_functions.py
Updated desmear so as to add the correct number for filling rows depending on NRBIN.
Should note that it would be more correct if nrskip were a multiple of nrbin - we can now have partial binned rows.  The indexing takes care of this if somewhat crudely.  
Exponential extrapolation can give negative values in IR3 and IR4 so a linear extrapolation has been added and made to be default.  Can sometimes give negative values above 90 km- I think we can live with it
UV1 can look weird in crop4 but this is Lindas flat field and not the desmearing.   Hopefully this will be gone when she makes better ones. 
I had a look at trying to make default filling from non cropped data but the variation is too large to make this easy - requires more work.
=> corrections to desmear and lin method

src/mats_l1_processing/L1_calibration_functions.py
Let myself get confused by Lindas non-flat fields and made an incorrect change-
Minor effect (might be more if using exp) but better to have it correct
=> fixing nrskip in tril matrix (had changed wrongly

src/mats_l1_processing/L1_calibration_functions.py
discovered that we had a conceptual problem in the filling and how it should be used. I don't think the previous version of the de-smear did anything at higher altitudes.
This version treats the fill and the remaining data in a correct manner. 
Some negative values night time seen in my tests but to be expected. 
Could remain a 1 line error in the indexing 
Suggest putting this through and letting it run over the weekend -  so we can check larger amounts of data
=> fix to desmear for cropped images

src/mats_l1_processing/read_parquet_functions.py
Indexing was implicitly done on `EXPDate` (or `TMHeaderTime`) before, this caused some strange behaviour if you wanted to do some things, e.g. it would not show up in df.columns. Now sorting is done on `TMHeaderTime` but index is set to simple numerical index before the dataframe is returned.
=> Changed indexing of read_ccd_data_in_interval

src/mats_l1_processing/read_parquet_functions.py
From the documentation:
```
Sort object by labels (along an axis).
Returns a new DataFrame sorted by label if `inplace` argument is
``False``, otherwise updates the original DataFrame and returns None.
...
inplace : bool, default False
Whether to modify the DataFrame rather than creating a new one.
```
That is to say, without `inplace=True` this line only produces waste heat.
=> Add `inplace=True` to `sort_index`

src/mats_l1_processing/L1_calibration_functions.py
`import numpy as np` is already done up top, unnecessary and possibly wasteful to import it again.
=> Remove spurious import

tests/test_gridding.py
updated the test function test_pixdeg to match the new values given by the new version of pixdeg (maximal angular difference of 0.004 deg in the y axis and 0.02 deg for the x axis) 
the test function  test_shift is not working
=> updated test_pixdeg

src/mats_l1_processing/L1_calibration_functions.py
Bump instrument data and make processing fail early when table data is missing.
I don't think this change will impact the manual work-flows, since the flag is `True` by default, but please check!
=> Bump instrument

l1b_lambda/level1b/handlers/level1b.py
When reading metadata from file header, the resulting keys and values are `bytes`, however, the columns in the dataset are strings. This lead to the updating of the metadata creating semi-duplicated column names instead of updating the existing, since _e.g._ `b"INNOSAT" != "INNOSAT"`. When saving as dataset all columns were saved, but either there, or when reading, all columns were converted to string, which caused actual duplicated columns, resulting in an unreadable dataset.
This encodes the keys and values if necessary, which should avoid the problem.
=> Fix bytes metadata names

src/mats_l1_processing/L1_calibration_functions.py
Adding a check in order to raise an error if no solar azimuth angle is given in the L1a data (if the value is nan)
=> Adding a check in order to raise an error if no nadir solar azimuth angle

tests/test_calibration.py
updating test_calibration_output, as the artifact correction is now the first correction to be applied in l1a to l1b processing, changing the output order for L1_calibrate. 
adding test for artifact correction in the test_calibration_output function 
removing test for flatfield correction
=> updating the test functions :

src/database_generation/artifact_correction.py
Adding code to generate the bias values needed for the artifact correction.
The database consists of several masks to be applied to the nadir images during L1a to L1b processing. The adequate mask is chosen depending on the nadir solar azimuth value
=> Artifact database generation

src/database_generation/run_make_flatfield.py, src/mats_l1_processing/L1_calibration_functions.py, tests/calibration_data_test.toml, tests/test_calibration.py
Fixed bug in L1_calibration functions, meanbin_image_with_BC.  It used to bin the wrong area when nrskip+nbin_r*nrow > 511. Now padding the image with copies of the last row before binning.
=> Fixed bug in L1_calibration functions

src/mats_l1_processing/L1_calibrate.py
Return errors. This is not strictly necessary, but will make the interface in the Lambda neater.
=> Return errors when skipping steps

src/database_generation/flatfield.py, src/database_generation/run_make_flatfield.py
changed so that flat fields without baffle are read in as the mean from 3 different images with different integration time, instead of from only one image.
Added 2 error fields: the std/(sqrt(N) of the three fields to desctibe the statistical error in the flatfield without baffle, and baffle-scalefield which is what the nonbaffled field are multiplied with to the the merged fields.
=> Flatfield avarages2

src/mats_l1_processing/L1_calibration_functions.py, src/mats_l1_processing/instrument.py
changed so that median filter of dark current was applied to the two coefficients of the linear fit  ( darkcurrent =
10 ** (self.log_a_img_avr_HSM * T + self.log_b_img_avr_HSM) see darkcurrent2d in instrument.py) instead of to the final dark current. This was done in order to get faster processing since the median filter is now only applied when the CCD of the instrument is initiated.
=> changed where median filter of dark current was applied. to make code faster.

src/mats_l1_processing/read_parquet_functions.py
Skip conversion of `ImageData` if `ImageCalibrated` is already in structure.
Resolves #213
=> Do not crash if image-data is missing
